//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FanSync.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FanSync.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudflare protection detected. Please configure the required fields to fix this..
        /// </summary>
        public static string err_cloudflare_detected {
            get {
                return ResourceManager.GetString("err_cloudflare_detected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FANBOXSESSID cookie is invalid..
        /// </summary>
        public static string err_fanbox_cookie {
            get {
                return ResourceManager.GetString("err_fanbox_cookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FanSync token is invalid..
        /// </summary>
        public static string err_fansync_token {
            get {
                return ResourceManager.GetString("err_fansync_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Fanbox cookie appears to have expired, please update it..
        /// </summary>
        public static string exc_fanbox_cookie {
            get {
                return ResourceManager.GetString("exc_fanbox_cookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FanSync token appears to have expired, please update it..
        /// </summary>
        public static string exc_fansync_token {
            get {
                return ResourceManager.GetString("exc_fansync_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The FanSync settings failed to load, do you want to reset them to the original values?.
        /// </summary>
        public static string exc_settings {
            get {
                return ResourceManager.GetString("exc_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string lbl_apply {
            get {
                return ResourceManager.GetString("lbl_apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string lbl_cancel {
            get {
                return ResourceManager.GetString("lbl_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cf__clearance Cookie:.
        /// </summary>
        public static string lbl_cf_clearance_cookie {
            get {
                return ResourceManager.GetString("lbl_cf_clearance_cookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cloudflare Clearance.
        /// </summary>
        public static string lbl_cloudflare_clearance {
            get {
                return ResourceManager.GetString("lbl_cloudflare_clearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string lbl_confirm {
            get {
                return ResourceManager.GetString("lbl_confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies.
        /// </summary>
        public static string lbl_cookies {
            get {
                return ResourceManager.GetString("lbl_cookies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cookies....
        /// </summary>
        public static string lbl_cookies_ {
            get {
                return ResourceManager.GetString("lbl_cookies_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error loading settings, please make sure the file contains valid json..
        /// </summary>
        public static string lbl_err_reload {
            get {
                return ResourceManager.GetString("lbl_err_reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string lbl_exit {
            get {
                return ResourceManager.GetString("lbl_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FANBOXSESSID cookie:.
        /// </summary>
        public static string lbl_fanbox_cookie {
            get {
                return ResourceManager.GetString("lbl_fanbox_cookie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FanSync token:.
        /// </summary>
        public static string lbl_fansync_token {
            get {
                return ResourceManager.GetString("lbl_fansync_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Supporters.
        /// </summary>
        public static string lbl_force_update {
            get {
                return ResourceManager.GetString("lbl_force_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        public static string lbl_headers {
            get {
                return ResourceManager.GetString("lbl_headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers....
        /// </summary>
        public static string lbl_headers_ {
            get {
                return ResourceManager.GetString("lbl_headers_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string lbl_loading {
            get {
                return ResourceManager.GetString("lbl_loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string lbl_name {
            get {
                return ResourceManager.GetString("lbl_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string lbl_not_available {
            get {
                return ResourceManager.GetString("lbl_not_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Settings.
        /// </summary>
        public static string lbl_reload_settings {
            get {
                return ResourceManager.GetString("lbl_reload_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string lbl_reset {
            get {
                return ResourceManager.GetString("lbl_reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Settings.
        /// </summary>
        public static string lbl_reset_settings {
            get {
                return ResourceManager.GetString("lbl_reset_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while getting pledge data from Fanbox..
        /// </summary>
        public static string lbl_status_fanbox_error {
            get {
                return ResourceManager.GetString("lbl_status_fanbox_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while uploading pledge data..
        /// </summary>
        public static string lbl_status_fansync_error {
            get {
                return ResourceManager.GetString("lbl_status_fansync_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Network error..
        /// </summary>
        public static string lbl_status_network_error {
            get {
                return ResourceManager.GetString("lbl_status_network_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully updated pledges..
        /// </summary>
        public static string lbl_status_success {
            get {
                return ResourceManager.GetString("lbl_status_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (unchanged).
        /// </summary>
        public static string lbl_unchanged {
            get {
                return ResourceManager.GetString("lbl_unchanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string lbl_uninstall {
            get {
                return ResourceManager.GetString("lbl_uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update available..
        /// </summary>
        public static string lbl_update_available {
            get {
                return ResourceManager.GetString("lbl_update_available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updating....
        /// </summary>
        public static string lbl_updating {
            get {
                return ResourceManager.GetString("lbl_updating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Agent:.
        /// </summary>
        public static string lbl_user_agent {
            get {
                return ResourceManager.GetString("lbl_user_agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string lbl_value {
            get {
                return ResourceManager.GetString("lbl_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FanSync has stopped being supported, please uninstall this application..
        /// </summary>
        public static string msg_out_of_service {
            get {
                return ResourceManager.GetString("msg_out_of_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FanSync still requires some configuration to finish setting up..
        /// </summary>
        public static string msg_setup {
            get {
                return ResourceManager.GetString("msg_setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There&apos;s a new version of the FanSync application, please update or you might run into some issues..
        /// </summary>
        public static string msg_update {
            get {
                return ResourceManager.GetString("msg_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string notify_exit {
            get {
                return ResourceManager.GetString("notify_exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string notify_settings {
            get {
                return ResourceManager.GetString("notify_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced.
        /// </summary>
        public static string tab_advanced {
            get {
                return ResourceManager.GetString("tab_advanced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string tab_settings {
            get {
                return ResourceManager.GetString("tab_settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string tab_status {
            get {
                return ResourceManager.GetString("tab_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FanSync - Error.
        /// </summary>
        public static string title_error {
            get {
                return ResourceManager.GetString("title_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FanSync.
        /// </summary>
        public static string title_main {
            get {
                return ResourceManager.GetString("title_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FanSync - Out of Service.
        /// </summary>
        public static string title_out_of_service {
            get {
                return ResourceManager.GetString("title_out_of_service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FanSync - Setup.
        /// </summary>
        public static string title_setup {
            get {
                return ResourceManager.GetString("title_setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FanSync - Update.
        /// </summary>
        public static string title_update {
            get {
                return ResourceManager.GetString("title_update", resourceCulture);
            }
        }
    }
}
